# Generated by Django 5.2.6 on 2025-09-13 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disciplines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите автора урока",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор урока",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="educational_module",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите модуль",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="disciplines.educationalmodule",
                verbose_name="Образовательный модуль",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите образовательную тему",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="disciplines.topic",
                verbose_name="Тема",
            ),
        ),
    ]
