# Generated by Django 5.2.6 on 2025-09-13 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="course_test",
            new_name="quiz",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="course",
            new_name="lesson",
        ),
    ]
